# OSX agents don't have nvm pre-installed, and installing it manually
# gives me a lot more control over testing packaging options
language: ruby

sudo: true

# Add in for Docker infrastructure
# ...but failed with 'could not find executable rpmbuild' when I tried it
#addons:
#  apt:
#    packages:
#      -rpm

os:
  - linux
  - osx

rvm: '1.9.3'

env:
  matrix:
    - MB_TEST_SPECS="NODE_VERSION=0.10|MB_TEST_PARAM=0.10"
    - MB_TEST_SPECS="NODE_VERSION=0.12|MB_TEST_PARAM=0.12"
    - MB_TEST_SPECS="NODE_VERSION=4.0|MB_TEST_PARAM=4.0"
  global:
    - SLOW_TEST_TIMEOUT_MS=5000
    # HEROKU_API_KEY
    - secure: "BQunTTpCSGjhIYiBAXKxuuOluJIhKXdW/94GCsPlK1N8Ln20/nj/0U4qnSH7yASWQWssVG4ttm/cAbjfi+3DS4KDLtBGK1i3IoM+cJ2ADCeG7BHsqJDB0f9JyAkULjIRdkqilzR/tyD+w78pPHd7QbfplLvqUcnt7HVxw9lp4PY="
    # AWS_ACCESS_KEY
    - secure: "H0iUwBPOwRf3+5HGqAXWU65dJIA+4SUltehM3+jiTXsqkxeHux3WqVOouaLlw2n8WaG9y1KMXEZzed6L8p8A3I6V2M+Y1n8qNYT8y/HjCTw4d3U0tiG6ef1ysIChdBOdlwXJT5GPLlLT0y+R4IgPfHd3DMx/aiEgT3O4gGZEchs="
    # NPM_API_KEY
    - secure: "pbVyYwERkTpwkpFTqXjwsMkNpulV0ZV1HbBZeEBhpWY7MjIjjASd/kDwDBr4ONuiicOQ3ToL4MeKxgI2bxjQdhDhfBvMt5XZV6V8X8xktwZQsnkc9klD0qr5raQ6MZdWQzx4nlsgFLHO9k0w8D/EzQbz25E4KAicpaYYwejyig8="

install:
  - echo $MB_TEST_SPECS | tr '|' '\n' > .mbrc
  - cat ./.mbrc
  - . ./.mbrc
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version

script:
  - echo "MB_TEST_PARAM: $MB_TEST_PARAM"
  #- ./build && scripts/travisDeploy
