language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'

env:
  global:
    secure: "J5vdNiybfYg9syfhHlu40YqVAmntfciXsdkNpnXkG2bVV3JMTQ6dPysMU8ZInsoOC3FCEtrO7ZxSvo3n9p8GHC3lMSg4NDfpsGwt2TckpeKBhzOTARhbyEIg2GNxPUh2cGkxMUXYRVW1KlTiPnWaSqsDsrak93CBVXu3B7dXmOI="

script: ./build

after_success:
  - echo "_auth = $npm_api_key" > ~/.npmrc
  - echo "email = brandon.byars@gmail.com" >> ~/.npmrc
  - echo >> ~/.npmrc
  - (cd server && npm publish)
