language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'

env:
  global:
    - secure: "X8vk5JI9JYpYWUViH1LNUmGP4iXn4CbkQiUMD3IWfZ1N3B1KJ9JmLak1pXReLUmenRscocX8sYdaIFBVYKQJId5Y38Q26nOEy92JixfmtZT01LpIOWXSmIRtjdS0GoIrxSG/cYhLx+6YGP2ZQoQr4SiXp3wa1hE2HkGAzX3mXeY="

script: ./build
