language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'

env:
  global:
    NPM_API_KEY:
      secure: "MY/g9ug4502AZPHMX+ehW0/lmea745weQ5IXyE/UgTfbgVxK44WrY7V09b9YUYoxm34aVCffDzz+cprBZKnVwNDgWj7dvCnDM58HwX4z00XlxfvnzzHrYRL3UCcIy2jl5Dp8Purtc3bDEPdQQGRglrq+98kSnFE5vThw25bLKto="
    COVERALLS_REPO_TOKEN:
      secure: "nLWa1EUU44PfEFXx8H2ZLz1rENOZ8e4wJ+5drcb63Yu3k0Qj6eTrGRU5dPuDHbw5mr609FgsOwIsbQeOmBpYLdaUbtHkX7rTeWUD9zsLnJDVoB2OBC4FY4owyxqYOSBAQVgbB8m7ITVUUr+GsyN1B+lC0Xcw7h05BtoNtnjAxbI="

script: ./build
