language: node_js
node_js:
- '0.10'
- '0.8'

env:
  global:
    - SLOW_TEST_TIMEOUT_MS=3000

script: ./build

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: jxAbZJqLE+mkhNJMlqQRRNqGsSkygb+Z0/AB3JghTZ1iDHfZYNTrFaGHCwOanW05MWAbrO7ntzaYQMHFlLQrqCuQfajQARUDiQWNfCpFtBszBYSrnsIoF1M7LNw00dRpQocwbGKX8Z+yaeaDS88ax6gTevKuF32Qlk9PcIyQTZw=
  app: mountebank
  on:
    repo: bbyars/mountebank
    node: 0.10
