language: node_js
node_js:
- '0.10'
rvm: '1.9.3'

matrix:
  allow_failures:
    - node: '0.8'
    - node: '0.11'

env:
  global:
  - SLOW_TEST_TIMEOUT_MS=4000
  # HEROKU_API_KEY
  - secure: "BQunTTpCSGjhIYiBAXKxuuOluJIhKXdW/94GCsPlK1N8Ln20/nj/0U4qnSH7yASWQWssVG4ttm/cAbjfi+3DS4KDLtBGK1i3IoM+cJ2ADCeG7BHsqJDB0f9JyAkULjIRdkqilzR/tyD+w78pPHd7QbfplLvqUcnt7HVxw9lp4PY="
  # AWS_ACCESS_KEY
  - secure: "H0iUwBPOwRf3+5HGqAXWU65dJIA+4SUltehM3+jiTXsqkxeHux3WqVOouaLlw2n8WaG9y1KMXEZzed6L8p8A3I6V2M+Y1n8qNYT8y/HjCTw4d3U0tiG6ef1ysIChdBOdlwXJT5GPLlLT0y+R4IgPfHd3DMx/aiEgT3O4gGZEchs="

script:
  - ./build
  - scripts/deploy

before_deploy:
  - #echo creating distributables
  - #mkdir packages
  - #gem install fpm
  - #sudo apt-get install rpm
  - #fpm -s npm -t deb -n mountebank dist
  - #fpm -s npm -t rpm -n mountebank dist
  - #mv *.deb packages
  - #mv *.rpm packages
  - #ls -al
  - #ls -al packages
  - #ls -al dist

deploy:
  - provider: npm
    skip_cleanup: true
    email: brandon.byars@gmail.com
    api_key:
      secure: AFCSL5AzR+toPEzXpI5JpvYUX3c0NFEXbU36gT+5CWUJaWn4YA+fXBcwRD2cLf1OAXkMK+zVyJa2IqTA2lMWl4c4HBEC71lkoFLGXiPXKUFwt6sGGeiSPOMUbWZ3+qp8TY+r0T6DKmlF2qglBkgLy3JMnan4hW1n6VMBIqazNKw=
    on:
      repo: bbyars/mountebank
      branch: v1.0.0
      node: '0.10'
