language: node_js
node_js:
- '0.10'
rvm: '1.9.3'

matrix:
  allow_failures:
    - node: '0.8'
    - node: '0.11'

env:
  global:
    - HEROKU_API_KEY:
        secure: jxAbZJqLE+mkhNJMlqQRRNqGsSkygb+Z0/AB3JghTZ1iDHfZYNTrFaGHCwOanW05MWAbrO7ntzaYQMHFlLQrqCuQfajQARUDiQWNfCpFtBszBYSrnsIoF1M7LNw00dRpQocwbGKX8Z+yaeaDS88ax6gTevKuF32Qlk9PcIyQTZw=
    - SLOW_TEST_TIMEOUT_MS=4000

script: ./build
after_success: bin/deploy

before_deploy:
  - #echo creating distributables
  - #mkdir packages
  - #gem install fpm
  - #sudo apt-get install rpm
  - #fpm -s npm -t deb -n mountebank dist
  - #fpm -s npm -t rpm -n mountebank dist
  - #mv *.deb packages
  - #mv *.rpm packages
  - #ls -al
  - #ls -al packages
  - #ls -al dist

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIE2GUJRUIHGE2PWA
    secret_access_key:
      secure: SsdssebrTZo07ZS5yOOBKBzBKlQK7SUqqHI/FTlXXxf15zBPW3/dtosjrf70ysKXwRbSCqji0lEuRA5opuUS32pzoy4tMOVGbLKCzcPoiVib1DpjT4E/EXMeShLiSiHSJYgf7gA5KsfBBZrT8em6T4Gymzr2S+wGi3ZyHRjPwUw=
    bucket: mountebank
    local-dir: packages
    upload-dir: v1.0
    on:
      repo: bbyars/mountebank
      branch: why-does-this-causes-the-next-deploy-to-hang
      node: '0.10'
  - provider: npm
    skip_cleanup: true
    email: brandon.byars@gmail.com
    api_key:
      secure: AFCSL5AzR+toPEzXpI5JpvYUX3c0NFEXbU36gT+5CWUJaWn4YA+fXBcwRD2cLf1OAXkMK+zVyJa2IqTA2lMWl4c4HBEC71lkoFLGXiPXKUFwt6sGGeiSPOMUbWZ3+qp8TY+r0T6DKmlF2qglBkgLy3JMnan4hW1n6VMBIqazNKw=
    on:
      repo: bbyars/mountebank
      branch: v1.0.0
      node: '0.10'
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: jxAbZJqLE+mkhNJMlqQRRNqGsSkygb+Z0/AB3JghTZ1iDHfZYNTrFaGHCwOanW05MWAbrO7ntzaYQMHFlLQrqCuQfajQARUDiQWNfCpFtBszBYSrnsIoF1M7LNw00dRpQocwbGKX8Z+yaeaDS88ax6gTevKuF32Qlk9PcIyQTZw=
    app: mountebank
    on:
      repo: bbyars/mountebank
      branch: v1.0.0
      node: '0.10'
  - provider: heroku
    strategy: git
    skip_cleanup: true
    api_key:
      secure: jxAbZJqLE+mkhNJMlqQRRNqGsSkygb+Z0/AB3JghTZ1iDHfZYNTrFaGHCwOanW05MWAbrO7ntzaYQMHFlLQrqCuQfajQARUDiQWNfCpFtBszBYSrnsIoF1M7LNw00dRpQocwbGKX8Z+yaeaDS88ax6gTevKuF32Qlk9PcIyQTZw=
    app: mountebank-dev
    on:
      repo: bbyars/mountebank
      branch: ignore
      node: '0.10'
