language: node_js
node_js:
- '0.10'
rvm: '1.9.3'

matrix:
  allow_failures:
    - node: '0.8'
    - node: '0.11'

env:
  global:
  - SLOW_TEST_TIMEOUT_MS=4000
  # HEROKU_API_KEY
  - secure: "BQunTTpCSGjhIYiBAXKxuuOluJIhKXdW/94GCsPlK1N8Ln20/nj/0U4qnSH7yASWQWssVG4ttm/cAbjfi+3DS4KDLtBGK1i3IoM+cJ2ADCeG7BHsqJDB0f9JyAkULjIRdkqilzR/tyD+w78pPHd7QbfplLvqUcnt7HVxw9lp4PY="
  # AWS_ACCESS_KEY
  - secure: "H0iUwBPOwRf3+5HGqAXWU65dJIA+4SUltehM3+jiTXsqkxeHux3WqVOouaLlw2n8WaG9y1KMXEZzed6L8p8A3I6V2M+Y1n8qNYT8y/HjCTw4d3U0tiG6ef1ysIChdBOdlwXJT5GPLlLT0y+R4IgPfHd3DMx/aiEgT3O4gGZEchs="
  # NPM_API_KEY
  - secure: "DQK4BOavLaTAEleQwj/f7tsKZmFWUItq/Az5RvGTNMpJPNrQyCp1VX3+4nAk9wDorsbdHHE9dbhUdfkzovtbyMwOtv1q0+/ULpDT7eOOxH7jZ/2LoBMEaY5EqbzWFWbLUIsirQGHFTvgFItwb84on2qjPi5pCnKTLJalgmOsk4Y="

script:
  - ./build
  - scripts/createDistributables
  - scripts/deploy
