language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'

env:
  global:
    secure: "X8vk5JI9JYpYWUViH1LNUmGP4iXn4CbkQiUMD3IWfZ1N3B1KJ9JmLak1pXReLUmenRscocX8sYdaIFBVYKQJId5Y38Q26nOEy92JixfmtZT01LpIOWXSmIRtjdS0GoIrxSG/cYhLx+6YGP2ZQoQr4SiXp3wa1hE2HkGAzX3mXeY="
    secure: "htFh2NmT7TZcYQOcgF4PLF8BC6TIqJWDc0ZEPNKw5xWKFJI/R0NVv6R9+ETF2oPW6uMaCTlyJNCzDTlATM62GH4X0yLERtaHCUshNlrmnwBKPWt2m5bFwP2zfhkrp6CJzPRl3S73RDZb7jrYSuPLwIFql6KAwQ9pf6D1e1OJePY="

script: ./build
