environment:
  SLOW_TEST_TIMEOUT_MS: 5000
  matrix:
      - nodejs_version: 0.10

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g grunt-cli
  - npm install

build_script:
  - node --version
  - npm --version
  - grunt help

test: off

