environment:
  SLOW_TEST_TIMEOUT_MS: 5000
  matrix:
      - nodejs_version: 0.10

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)

test_script:
  - cmd: build.bat

build: off
